// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entity_schema.proto

package com.whosbean.newim.entity;

/**
 * Protobuf type {@code im.ChatMessage}
 */
public  final class ChatMessage extends
    com.google.protobuf.GeneratedMessage
    implements ChatMessageOrBuilder {
  // Use ChatMessage.newBuilder() to construct.
  private ChatMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private ChatMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final ChatMessage defaultInstance;
  public static ChatMessage getDefaultInstance() {
    return defaultInstance;
  }

  public ChatMessage getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private ChatMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            bitField0_ |= 0x00000001;
            boxid_ = input.readBytes();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            group_ = input.readInt32();
            break;
          }
          case 26: {
            bitField0_ |= 0x00000004;
            uuid_ = input.readBytes();
            break;
          }
          case 34: {
            bitField0_ |= 0x00000008;
            sender_ = input.readBytes();
            break;
          }
          case 42: {
            bitField0_ |= 0x00000010;
            receiver_ = input.readBytes();
            break;
          }
          case 50: {
            bitField0_ |= 0x00000020;
            body_ = input.readBytes();
            break;
          }
          case 56: {
            int rawValue = input.readEnum();
            com.whosbean.newim.entity.ChatMessage.MessageType value = com.whosbean.newim.entity.ChatMessage.MessageType.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(7, rawValue);
            } else {
              bitField0_ |= 0x00000040;
              mtype_ = value;
            }
            break;
          }
          case 64: {
            int rawValue = input.readEnum();
            com.whosbean.newim.entity.ChatMessage.ChatOp value = com.whosbean.newim.entity.ChatMessage.ChatOp.valueOf(rawValue);
            if (value == null) {
              unknownFields.mergeVarintField(8, rawValue);
            } else {
              bitField0_ |= 0x00000080;
              op_ = value;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.whosbean.newim.entity.EntitySchema.internal_static_im_ChatMessage_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.whosbean.newim.entity.EntitySchema.internal_static_im_ChatMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.whosbean.newim.entity.ChatMessage.class, com.whosbean.newim.entity.ChatMessage.Builder.class);
  }

  public static com.google.protobuf.Parser<ChatMessage> PARSER =
      new com.google.protobuf.AbstractParser<ChatMessage>() {
    public ChatMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ChatMessage(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<ChatMessage> getParserForType() {
    return PARSER;
  }

  /**
   * Protobuf enum {@code im.ChatMessage.MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SmallText = 0;</code>
     */
    SmallText(0, 0),
    /**
     * <code>LongText = 1;</code>
     */
    LongText(1, 1),
    /**
     * <code>AUDIO = 2;</code>
     */
    AUDIO(2, 2),
    /**
     * <code>IMAGE = 3;</code>
     */
    IMAGE(3, 3),
    /**
     * <code>VIDEO = 4;</code>
     */
    VIDEO(4, 4),
    /**
     * <code>FILE = 5;</code>
     */
    FILE(5, 5),
    /**
     * <code>LINK = 6;</code>
     */
    LINK(6, 6),
    /**
     * <code>SYNC = 7;</code>
     */
    SYNC(7, 7),
    ;

    /**
     * <code>SmallText = 0;</code>
     */
    public static final int SmallText_VALUE = 0;
    /**
     * <code>LongText = 1;</code>
     */
    public static final int LongText_VALUE = 1;
    /**
     * <code>AUDIO = 2;</code>
     */
    public static final int AUDIO_VALUE = 2;
    /**
     * <code>IMAGE = 3;</code>
     */
    public static final int IMAGE_VALUE = 3;
    /**
     * <code>VIDEO = 4;</code>
     */
    public static final int VIDEO_VALUE = 4;
    /**
     * <code>FILE = 5;</code>
     */
    public static final int FILE_VALUE = 5;
    /**
     * <code>LINK = 6;</code>
     */
    public static final int LINK_VALUE = 6;
    /**
     * <code>SYNC = 7;</code>
     */
    public static final int SYNC_VALUE = 7;


    public final int getNumber() { return value; }

    public static MessageType valueOf(int value) {
      switch (value) {
        case 0: return SmallText;
        case 1: return LongText;
        case 2: return AUDIO;
        case 3: return IMAGE;
        case 4: return VIDEO;
        case 5: return FILE;
        case 6: return LINK;
        case 7: return SYNC;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.whosbean.newim.entity.ChatMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MessageType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:im.ChatMessage.MessageType)
  }

  /**
   * Protobuf enum {@code im.ChatMessage.ChatOp}
   */
  public enum ChatOp
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>JOIN = 0;</code>
     */
    JOIN(0, 0),
    /**
     * <code>QUIT = 1;</code>
     */
    QUIT(1, 1),
    /**
     * <code>CHAT = 2;</code>
     */
    CHAT(2, 2),
    /**
     * <code>ACK = 3;</code>
     */
    ACK(3, 3),
    ;

    /**
     * <code>JOIN = 0;</code>
     */
    public static final int JOIN_VALUE = 0;
    /**
     * <code>QUIT = 1;</code>
     */
    public static final int QUIT_VALUE = 1;
    /**
     * <code>CHAT = 2;</code>
     */
    public static final int CHAT_VALUE = 2;
    /**
     * <code>ACK = 3;</code>
     */
    public static final int ACK_VALUE = 3;


    public final int getNumber() { return value; }

    public static ChatOp valueOf(int value) {
      switch (value) {
        case 0: return JOIN;
        case 1: return QUIT;
        case 2: return CHAT;
        case 3: return ACK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ChatOp>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ChatOp>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ChatOp>() {
            public ChatOp findValueByNumber(int number) {
              return ChatOp.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.whosbean.newim.entity.ChatMessage.getDescriptor().getEnumTypes().get(1);
    }

    private static final ChatOp[] VALUES = values();

    public static ChatOp valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ChatOp(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:im.ChatMessage.ChatOp)
  }

  private int bitField0_;
  // required string boxid = 1;
  public static final int BOXID_FIELD_NUMBER = 1;
  private java.lang.Object boxid_;
  /**
   * <code>required string boxid = 1;</code>
   */
  public boolean hasBoxid() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required string boxid = 1;</code>
   */
  public java.lang.String getBoxid() {
    java.lang.Object ref = boxid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        boxid_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string boxid = 1;</code>
   */
  public com.google.protobuf.ByteString
      getBoxidBytes() {
    java.lang.Object ref = boxid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      boxid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // required int32 group = 2 [default = 0];
  public static final int GROUP_FIELD_NUMBER = 2;
  private int group_;
  /**
   * <code>required int32 group = 2 [default = 0];</code>
   */
  public boolean hasGroup() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required int32 group = 2 [default = 0];</code>
   */
  public int getGroup() {
    return group_;
  }

  // optional string uuid = 3;
  public static final int UUID_FIELD_NUMBER = 3;
  private java.lang.Object uuid_;
  /**
   * <code>optional string uuid = 3;</code>
   */
  public boolean hasUuid() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional string uuid = 3;</code>
   */
  public java.lang.String getUuid() {
    java.lang.Object ref = uuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        uuid_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string uuid = 3;</code>
   */
  public com.google.protobuf.ByteString
      getUuidBytes() {
    java.lang.Object ref = uuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string sender = 4;
  public static final int SENDER_FIELD_NUMBER = 4;
  private java.lang.Object sender_;
  /**
   * <code>optional string sender = 4;</code>
   */
  public boolean hasSender() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional string sender = 4;</code>
   */
  public java.lang.String getSender() {
    java.lang.Object ref = sender_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        sender_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string sender = 4;</code>
   */
  public com.google.protobuf.ByteString
      getSenderBytes() {
    java.lang.Object ref = sender_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sender_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string receiver = 5;
  public static final int RECEIVER_FIELD_NUMBER = 5;
  private java.lang.Object receiver_;
  /**
   * <code>optional string receiver = 5;</code>
   */
  public boolean hasReceiver() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional string receiver = 5;</code>
   */
  public java.lang.String getReceiver() {
    java.lang.Object ref = receiver_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        receiver_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string receiver = 5;</code>
   */
  public com.google.protobuf.ByteString
      getReceiverBytes() {
    java.lang.Object ref = receiver_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      receiver_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string body = 6;
  public static final int BODY_FIELD_NUMBER = 6;
  private java.lang.Object body_;
  /**
   * <code>optional string body = 6;</code>
   */
  public boolean hasBody() {
    return ((bitField0_ & 0x00000020) == 0x00000020);
  }
  /**
   * <code>optional string body = 6;</code>
   */
  public java.lang.String getBody() {
    java.lang.Object ref = body_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        body_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string body = 6;</code>
   */
  public com.google.protobuf.ByteString
      getBodyBytes() {
    java.lang.Object ref = body_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      body_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // required .im.ChatMessage.MessageType mtype = 7 [default = SYNC];
  public static final int MTYPE_FIELD_NUMBER = 7;
  private com.whosbean.newim.entity.ChatMessage.MessageType mtype_;
  /**
   * <code>required .im.ChatMessage.MessageType mtype = 7 [default = SYNC];</code>
   */
  public boolean hasMtype() {
    return ((bitField0_ & 0x00000040) == 0x00000040);
  }
  /**
   * <code>required .im.ChatMessage.MessageType mtype = 7 [default = SYNC];</code>
   */
  public com.whosbean.newim.entity.ChatMessage.MessageType getMtype() {
    return mtype_;
  }

  // required .im.ChatMessage.ChatOp op = 8 [default = ACK];
  public static final int OP_FIELD_NUMBER = 8;
  private com.whosbean.newim.entity.ChatMessage.ChatOp op_;
  /**
   * <code>required .im.ChatMessage.ChatOp op = 8 [default = ACK];</code>
   */
  public boolean hasOp() {
    return ((bitField0_ & 0x00000080) == 0x00000080);
  }
  /**
   * <code>required .im.ChatMessage.ChatOp op = 8 [default = ACK];</code>
   */
  public com.whosbean.newim.entity.ChatMessage.ChatOp getOp() {
    return op_;
  }

  private void initFields() {
    boxid_ = "";
    group_ = 0;
    uuid_ = "";
    sender_ = "";
    receiver_ = "";
    body_ = "";
    mtype_ = com.whosbean.newim.entity.ChatMessage.MessageType.SYNC;
    op_ = com.whosbean.newim.entity.ChatMessage.ChatOp.ACK;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    if (!hasBoxid()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasGroup()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasMtype()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasOp()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getBoxidBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt32(2, group_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeBytes(3, getUuidBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeBytes(4, getSenderBytes());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeBytes(5, getReceiverBytes());
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      output.writeBytes(6, getBodyBytes());
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      output.writeEnum(7, mtype_.getNumber());
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      output.writeEnum(8, op_.getNumber());
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getBoxidBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, group_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, getUuidBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, getSenderBytes());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, getReceiverBytes());
    }
    if (((bitField0_ & 0x00000020) == 0x00000020)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(6, getBodyBytes());
    }
    if (((bitField0_ & 0x00000040) == 0x00000040)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, mtype_.getNumber());
    }
    if (((bitField0_ & 0x00000080) == 0x00000080)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(8, op_.getNumber());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.whosbean.newim.entity.ChatMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.whosbean.newim.entity.ChatMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.whosbean.newim.entity.ChatMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.whosbean.newim.entity.ChatMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.whosbean.newim.entity.ChatMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.whosbean.newim.entity.ChatMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.whosbean.newim.entity.ChatMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.whosbean.newim.entity.ChatMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.whosbean.newim.entity.ChatMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.whosbean.newim.entity.ChatMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.whosbean.newim.entity.ChatMessage prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code im.ChatMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements com.whosbean.newim.entity.ChatMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.whosbean.newim.entity.EntitySchema.internal_static_im_ChatMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.whosbean.newim.entity.EntitySchema.internal_static_im_ChatMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.whosbean.newim.entity.ChatMessage.class, com.whosbean.newim.entity.ChatMessage.Builder.class);
    }

    // Construct using com.whosbean.newim.entity.ChatMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      boxid_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      group_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      uuid_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      sender_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      receiver_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      body_ = "";
      bitField0_ = (bitField0_ & ~0x00000020);
      mtype_ = com.whosbean.newim.entity.ChatMessage.MessageType.SYNC;
      bitField0_ = (bitField0_ & ~0x00000040);
      op_ = com.whosbean.newim.entity.ChatMessage.ChatOp.ACK;
      bitField0_ = (bitField0_ & ~0x00000080);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.whosbean.newim.entity.EntitySchema.internal_static_im_ChatMessage_descriptor;
    }

    public com.whosbean.newim.entity.ChatMessage getDefaultInstanceForType() {
      return com.whosbean.newim.entity.ChatMessage.getDefaultInstance();
    }

    public com.whosbean.newim.entity.ChatMessage build() {
      com.whosbean.newim.entity.ChatMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.whosbean.newim.entity.ChatMessage buildPartial() {
      com.whosbean.newim.entity.ChatMessage result = new com.whosbean.newim.entity.ChatMessage(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.boxid_ = boxid_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.group_ = group_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.uuid_ = uuid_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.sender_ = sender_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.receiver_ = receiver_;
      if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
        to_bitField0_ |= 0x00000020;
      }
      result.body_ = body_;
      if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
        to_bitField0_ |= 0x00000040;
      }
      result.mtype_ = mtype_;
      if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
        to_bitField0_ |= 0x00000080;
      }
      result.op_ = op_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.whosbean.newim.entity.ChatMessage) {
        return mergeFrom((com.whosbean.newim.entity.ChatMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.whosbean.newim.entity.ChatMessage other) {
      if (other == com.whosbean.newim.entity.ChatMessage.getDefaultInstance()) return this;
      if (other.hasBoxid()) {
        bitField0_ |= 0x00000001;
        boxid_ = other.boxid_;
        onChanged();
      }
      if (other.hasGroup()) {
        setGroup(other.getGroup());
      }
      if (other.hasUuid()) {
        bitField0_ |= 0x00000004;
        uuid_ = other.uuid_;
        onChanged();
      }
      if (other.hasSender()) {
        bitField0_ |= 0x00000008;
        sender_ = other.sender_;
        onChanged();
      }
      if (other.hasReceiver()) {
        bitField0_ |= 0x00000010;
        receiver_ = other.receiver_;
        onChanged();
      }
      if (other.hasBody()) {
        bitField0_ |= 0x00000020;
        body_ = other.body_;
        onChanged();
      }
      if (other.hasMtype()) {
        setMtype(other.getMtype());
      }
      if (other.hasOp()) {
        setOp(other.getOp());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasBoxid()) {
        
        return false;
      }
      if (!hasGroup()) {
        
        return false;
      }
      if (!hasMtype()) {
        
        return false;
      }
      if (!hasOp()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.whosbean.newim.entity.ChatMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.whosbean.newim.entity.ChatMessage) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // required string boxid = 1;
    private java.lang.Object boxid_ = "";
    /**
     * <code>required string boxid = 1;</code>
     */
    public boolean hasBoxid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string boxid = 1;</code>
     */
    public java.lang.String getBoxid() {
      java.lang.Object ref = boxid_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        boxid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string boxid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBoxidBytes() {
      java.lang.Object ref = boxid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        boxid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string boxid = 1;</code>
     */
    public Builder setBoxid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      boxid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string boxid = 1;</code>
     */
    public Builder clearBoxid() {
      bitField0_ = (bitField0_ & ~0x00000001);
      boxid_ = getDefaultInstance().getBoxid();
      onChanged();
      return this;
    }
    /**
     * <code>required string boxid = 1;</code>
     */
    public Builder setBoxidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      boxid_ = value;
      onChanged();
      return this;
    }

    // required int32 group = 2 [default = 0];
    private int group_ ;
    /**
     * <code>required int32 group = 2 [default = 0];</code>
     */
    public boolean hasGroup() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 group = 2 [default = 0];</code>
     */
    public int getGroup() {
      return group_;
    }
    /**
     * <code>required int32 group = 2 [default = 0];</code>
     */
    public Builder setGroup(int value) {
      bitField0_ |= 0x00000002;
      group_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 group = 2 [default = 0];</code>
     */
    public Builder clearGroup() {
      bitField0_ = (bitField0_ & ~0x00000002);
      group_ = 0;
      onChanged();
      return this;
    }

    // optional string uuid = 3;
    private java.lang.Object uuid_ = "";
    /**
     * <code>optional string uuid = 3;</code>
     */
    public boolean hasUuid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string uuid = 3;</code>
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        uuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string uuid = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string uuid = 3;</code>
     */
    public Builder setUuid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      uuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string uuid = 3;</code>
     */
    public Builder clearUuid() {
      bitField0_ = (bitField0_ & ~0x00000004);
      uuid_ = getDefaultInstance().getUuid();
      onChanged();
      return this;
    }
    /**
     * <code>optional string uuid = 3;</code>
     */
    public Builder setUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      uuid_ = value;
      onChanged();
      return this;
    }

    // optional string sender = 4;
    private java.lang.Object sender_ = "";
    /**
     * <code>optional string sender = 4;</code>
     */
    public boolean hasSender() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string sender = 4;</code>
     */
    public java.lang.String getSender() {
      java.lang.Object ref = sender_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        sender_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string sender = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSenderBytes() {
      java.lang.Object ref = sender_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string sender = 4;</code>
     */
    public Builder setSender(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      sender_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string sender = 4;</code>
     */
    public Builder clearSender() {
      bitField0_ = (bitField0_ & ~0x00000008);
      sender_ = getDefaultInstance().getSender();
      onChanged();
      return this;
    }
    /**
     * <code>optional string sender = 4;</code>
     */
    public Builder setSenderBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      sender_ = value;
      onChanged();
      return this;
    }

    // optional string receiver = 5;
    private java.lang.Object receiver_ = "";
    /**
     * <code>optional string receiver = 5;</code>
     */
    public boolean hasReceiver() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string receiver = 5;</code>
     */
    public java.lang.String getReceiver() {
      java.lang.Object ref = receiver_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        receiver_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string receiver = 5;</code>
     */
    public com.google.protobuf.ByteString
        getReceiverBytes() {
      java.lang.Object ref = receiver_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiver_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string receiver = 5;</code>
     */
    public Builder setReceiver(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      receiver_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string receiver = 5;</code>
     */
    public Builder clearReceiver() {
      bitField0_ = (bitField0_ & ~0x00000010);
      receiver_ = getDefaultInstance().getReceiver();
      onChanged();
      return this;
    }
    /**
     * <code>optional string receiver = 5;</code>
     */
    public Builder setReceiverBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      receiver_ = value;
      onChanged();
      return this;
    }

    // optional string body = 6;
    private java.lang.Object body_ = "";
    /**
     * <code>optional string body = 6;</code>
     */
    public boolean hasBody() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string body = 6;</code>
     */
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        body_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string body = 6;</code>
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string body = 6;</code>
     */
    public Builder setBody(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      body_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string body = 6;</code>
     */
    public Builder clearBody() {
      bitField0_ = (bitField0_ & ~0x00000020);
      body_ = getDefaultInstance().getBody();
      onChanged();
      return this;
    }
    /**
     * <code>optional string body = 6;</code>
     */
    public Builder setBodyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      body_ = value;
      onChanged();
      return this;
    }

    // required .im.ChatMessage.MessageType mtype = 7 [default = SYNC];
    private com.whosbean.newim.entity.ChatMessage.MessageType mtype_ = com.whosbean.newim.entity.ChatMessage.MessageType.SYNC;
    /**
     * <code>required .im.ChatMessage.MessageType mtype = 7 [default = SYNC];</code>
     */
    public boolean hasMtype() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required .im.ChatMessage.MessageType mtype = 7 [default = SYNC];</code>
     */
    public com.whosbean.newim.entity.ChatMessage.MessageType getMtype() {
      return mtype_;
    }
    /**
     * <code>required .im.ChatMessage.MessageType mtype = 7 [default = SYNC];</code>
     */
    public Builder setMtype(com.whosbean.newim.entity.ChatMessage.MessageType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000040;
      mtype_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required .im.ChatMessage.MessageType mtype = 7 [default = SYNC];</code>
     */
    public Builder clearMtype() {
      bitField0_ = (bitField0_ & ~0x00000040);
      mtype_ = com.whosbean.newim.entity.ChatMessage.MessageType.SYNC;
      onChanged();
      return this;
    }

    // required .im.ChatMessage.ChatOp op = 8 [default = ACK];
    private com.whosbean.newim.entity.ChatMessage.ChatOp op_ = com.whosbean.newim.entity.ChatMessage.ChatOp.ACK;
    /**
     * <code>required .im.ChatMessage.ChatOp op = 8 [default = ACK];</code>
     */
    public boolean hasOp() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required .im.ChatMessage.ChatOp op = 8 [default = ACK];</code>
     */
    public com.whosbean.newim.entity.ChatMessage.ChatOp getOp() {
      return op_;
    }
    /**
     * <code>required .im.ChatMessage.ChatOp op = 8 [default = ACK];</code>
     */
    public Builder setOp(com.whosbean.newim.entity.ChatMessage.ChatOp value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000080;
      op_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required .im.ChatMessage.ChatOp op = 8 [default = ACK];</code>
     */
    public Builder clearOp() {
      bitField0_ = (bitField0_ & ~0x00000080);
      op_ = com.whosbean.newim.entity.ChatMessage.ChatOp.ACK;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:im.ChatMessage)
  }

  static {
    defaultInstance = new ChatMessage(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:im.ChatMessage)
}

