// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entity_schema.proto

package com.whosbean.newim.entity;

/**
 * Protobuf type {@code im.ChatStatus}
 */
public  final class ChatStatus extends
    com.google.protobuf.GeneratedMessage
    implements ChatStatusOrBuilder {
  // Use ChatStatus.newBuilder() to construct.
  private ChatStatus(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private ChatStatus(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final ChatStatus defaultInstance;
  public static ChatStatus getDefaultInstance() {
    return defaultInstance;
  }

  public ChatStatus getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private ChatStatus(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            bitField0_ |= 0x00000001;
            sender_ = input.readBytes();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            syncMark_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.whosbean.newim.entity.EntitySchema.internal_static_im_ChatStatus_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.whosbean.newim.entity.EntitySchema.internal_static_im_ChatStatus_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.whosbean.newim.entity.ChatStatus.class, com.whosbean.newim.entity.ChatStatus.Builder.class);
  }

  public static com.google.protobuf.Parser<ChatStatus> PARSER =
      new com.google.protobuf.AbstractParser<ChatStatus>() {
    public ChatStatus parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ChatStatus(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<ChatStatus> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // required string sender = 1;
  public static final int SENDER_FIELD_NUMBER = 1;
  private java.lang.Object sender_;
  /**
   * <code>required string sender = 1;</code>
   */
  public boolean hasSender() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required string sender = 1;</code>
   */
  public java.lang.String getSender() {
    java.lang.Object ref = sender_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        sender_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string sender = 1;</code>
   */
  public com.google.protobuf.ByteString
      getSenderBytes() {
    java.lang.Object ref = sender_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sender_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // required int32 syncMark = 2;
  public static final int SYNCMARK_FIELD_NUMBER = 2;
  private int syncMark_;
  /**
   * <code>required int32 syncMark = 2;</code>
   */
  public boolean hasSyncMark() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>required int32 syncMark = 2;</code>
   */
  public int getSyncMark() {
    return syncMark_;
  }

  private void initFields() {
    sender_ = "";
    syncMark_ = 0;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    if (!hasSender()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (!hasSyncMark()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getSenderBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt32(2, syncMark_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getSenderBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, syncMark_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.whosbean.newim.entity.ChatStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.whosbean.newim.entity.ChatStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.whosbean.newim.entity.ChatStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.whosbean.newim.entity.ChatStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.whosbean.newim.entity.ChatStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.whosbean.newim.entity.ChatStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.whosbean.newim.entity.ChatStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.whosbean.newim.entity.ChatStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.whosbean.newim.entity.ChatStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.whosbean.newim.entity.ChatStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.whosbean.newim.entity.ChatStatus prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code im.ChatStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements com.whosbean.newim.entity.ChatStatusOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.whosbean.newim.entity.EntitySchema.internal_static_im_ChatStatus_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.whosbean.newim.entity.EntitySchema.internal_static_im_ChatStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.whosbean.newim.entity.ChatStatus.class, com.whosbean.newim.entity.ChatStatus.Builder.class);
    }

    // Construct using com.whosbean.newim.entity.ChatStatus.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      sender_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      syncMark_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.whosbean.newim.entity.EntitySchema.internal_static_im_ChatStatus_descriptor;
    }

    public com.whosbean.newim.entity.ChatStatus getDefaultInstanceForType() {
      return com.whosbean.newim.entity.ChatStatus.getDefaultInstance();
    }

    public com.whosbean.newim.entity.ChatStatus build() {
      com.whosbean.newim.entity.ChatStatus result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.whosbean.newim.entity.ChatStatus buildPartial() {
      com.whosbean.newim.entity.ChatStatus result = new com.whosbean.newim.entity.ChatStatus(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.sender_ = sender_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.syncMark_ = syncMark_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.whosbean.newim.entity.ChatStatus) {
        return mergeFrom((com.whosbean.newim.entity.ChatStatus)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.whosbean.newim.entity.ChatStatus other) {
      if (other == com.whosbean.newim.entity.ChatStatus.getDefaultInstance()) return this;
      if (other.hasSender()) {
        bitField0_ |= 0x00000001;
        sender_ = other.sender_;
        onChanged();
      }
      if (other.hasSyncMark()) {
        setSyncMark(other.getSyncMark());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasSender()) {
        
        return false;
      }
      if (!hasSyncMark()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.whosbean.newim.entity.ChatStatus parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.whosbean.newim.entity.ChatStatus) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // required string sender = 1;
    private java.lang.Object sender_ = "";
    /**
     * <code>required string sender = 1;</code>
     */
    public boolean hasSender() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string sender = 1;</code>
     */
    public java.lang.String getSender() {
      java.lang.Object ref = sender_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        sender_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string sender = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSenderBytes() {
      java.lang.Object ref = sender_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string sender = 1;</code>
     */
    public Builder setSender(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      sender_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string sender = 1;</code>
     */
    public Builder clearSender() {
      bitField0_ = (bitField0_ & ~0x00000001);
      sender_ = getDefaultInstance().getSender();
      onChanged();
      return this;
    }
    /**
     * <code>required string sender = 1;</code>
     */
    public Builder setSenderBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      sender_ = value;
      onChanged();
      return this;
    }

    // required int32 syncMark = 2;
    private int syncMark_ ;
    /**
     * <code>required int32 syncMark = 2;</code>
     */
    public boolean hasSyncMark() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 syncMark = 2;</code>
     */
    public int getSyncMark() {
      return syncMark_;
    }
    /**
     * <code>required int32 syncMark = 2;</code>
     */
    public Builder setSyncMark(int value) {
      bitField0_ |= 0x00000002;
      syncMark_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int32 syncMark = 2;</code>
     */
    public Builder clearSyncMark() {
      bitField0_ = (bitField0_ & ~0x00000002);
      syncMark_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:im.ChatStatus)
  }

  static {
    defaultInstance = new ChatStatus(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:im.ChatStatus)
}

