// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entity_schema.proto

package com.whosbean.newim.entity;

public final class EntitySchema {
  private EntitySchema() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_im_ChatMessage_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_im_ChatMessage_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_im_ChatStatus_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_im_ChatStatus_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_im_ExchangeMessage_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_im_ExchangeMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023entity_schema.proto\022\002im\"\343\002\n\013ChatMessag" +
      "e\022\r\n\005boxid\030\001 \002(\t\022\020\n\005group\030\002 \002(\005:\0010\022\014\n\004uu" +
      "id\030\003 \001(\t\022\016\n\006sender\030\004 \001(\t\022\020\n\010receiver\030\005 \001" +
      "(\t\022\014\n\004body\030\006 \001(\t\0220\n\005mtype\030\007 \002(\0162\033.im.Cha" +
      "tMessage.MessageType:\004SYNC\022\'\n\002op\030\010 \002(\0162\026" +
      ".im.ChatMessage.ChatOp:\003ACK\"i\n\013MessageTy" +
      "pe\022\r\n\tSmallText\020\000\022\014\n\010LongText\020\001\022\t\n\005AUDIO" +
      "\020\002\022\t\n\005IMAGE\020\003\022\t\n\005VIDEO\020\004\022\010\n\004FILE\020\005\022\010\n\004LI" +
      "NK\020\006\022\010\n\004SYNC\020\007\"/\n\006ChatOp\022\010\n\004JOIN\020\000\022\010\n\004QU" +
      "IT\020\001\022\010\n\004CHAT\020\002\022\007\n\003ACK\020\003\".\n\nChatStatus\022\016\n",
      "\006sender\030\001 \002(\t\022\020\n\010syncMark\030\002 \002(\005\"\177\n\017Excha" +
      "ngeMessage\022\021\n\tmessageId\030\001 \002(\t\022\017\n\007message" +
      "\030\002 \001(\t\022\020\n\010chatPath\030\003 \001(\t\022\022\n\nchatRoomId\030\004" +
      " \001(\t\022\017\n\007msgPath\030\005 \001(\t\022\021\n\tchannelId\030\006 \003(\005" +
      "B\035\n\031com.whosbean.newim.entityP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_im_ChatMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_im_ChatMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_im_ChatMessage_descriptor,
              new java.lang.String[] { "Boxid", "Group", "Uuid", "Sender", "Receiver", "Body", "Mtype", "Op", });
          internal_static_im_ChatStatus_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_im_ChatStatus_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_im_ChatStatus_descriptor,
              new java.lang.String[] { "Sender", "SyncMark", });
          internal_static_im_ExchangeMessage_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_im_ExchangeMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_im_ExchangeMessage_descriptor,
              new java.lang.String[] { "MessageId", "Message", "ChatPath", "ChatRoomId", "MsgPath", "ChannelId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
