// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entity_schema.proto

package com.whosbean.newim.entity;

/**
 * Protobuf type {@code im.ExchangeMessage}
 */
public  final class ExchangeMessage extends
    com.google.protobuf.GeneratedMessage
    implements ExchangeMessageOrBuilder {
  // Use ExchangeMessage.newBuilder() to construct.
  private ExchangeMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private ExchangeMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final ExchangeMessage defaultInstance;
  public static ExchangeMessage getDefaultInstance() {
    return defaultInstance;
  }

  public ExchangeMessage getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private ExchangeMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            bitField0_ |= 0x00000001;
            messageId_ = input.readBytes();
            break;
          }
          case 18: {
            bitField0_ |= 0x00000002;
            message_ = input.readBytes();
            break;
          }
          case 26: {
            bitField0_ |= 0x00000004;
            chatPath_ = input.readBytes();
            break;
          }
          case 34: {
            bitField0_ |= 0x00000008;
            chatRoomId_ = input.readBytes();
            break;
          }
          case 42: {
            bitField0_ |= 0x00000010;
            msgPath_ = input.readBytes();
            break;
          }
          case 48: {
            if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
              channelId_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000020;
            }
            channelId_.add(input.readInt32());
            break;
          }
          case 50: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000020) == 0x00000020) && input.getBytesUntilLimit() > 0) {
              channelId_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000020;
            }
            while (input.getBytesUntilLimit() > 0) {
              channelId_.add(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
        channelId_ = java.util.Collections.unmodifiableList(channelId_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.whosbean.newim.entity.EntitySchema.internal_static_im_ExchangeMessage_descriptor;
  }

  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.whosbean.newim.entity.EntitySchema.internal_static_im_ExchangeMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.whosbean.newim.entity.ExchangeMessage.class, com.whosbean.newim.entity.ExchangeMessage.Builder.class);
  }

  public static com.google.protobuf.Parser<ExchangeMessage> PARSER =
      new com.google.protobuf.AbstractParser<ExchangeMessage>() {
    public ExchangeMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ExchangeMessage(input, extensionRegistry);
    }
  };

  @java.lang.Override
  public com.google.protobuf.Parser<ExchangeMessage> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // required string messageId = 1;
  public static final int MESSAGEID_FIELD_NUMBER = 1;
  private java.lang.Object messageId_;
  /**
   * <code>required string messageId = 1;</code>
   */
  public boolean hasMessageId() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required string messageId = 1;</code>
   */
  public java.lang.String getMessageId() {
    java.lang.Object ref = messageId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        messageId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string messageId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getMessageIdBytes() {
    java.lang.Object ref = messageId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      messageId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string message = 2;
  public static final int MESSAGE_FIELD_NUMBER = 2;
  private java.lang.Object message_;
  /**
   * <code>optional string message = 2;</code>
   */
  public boolean hasMessage() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional string message = 2;</code>
   */
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        message_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string message = 2;</code>
   */
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string chatPath = 3;
  public static final int CHATPATH_FIELD_NUMBER = 3;
  private java.lang.Object chatPath_;
  /**
   * <code>optional string chatPath = 3;</code>
   */
  public boolean hasChatPath() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <code>optional string chatPath = 3;</code>
   */
  public java.lang.String getChatPath() {
    java.lang.Object ref = chatPath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        chatPath_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string chatPath = 3;</code>
   */
  public com.google.protobuf.ByteString
      getChatPathBytes() {
    java.lang.Object ref = chatPath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      chatPath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string chatRoomId = 4;
  public static final int CHATROOMID_FIELD_NUMBER = 4;
  private java.lang.Object chatRoomId_;
  /**
   * <code>optional string chatRoomId = 4;</code>
   */
  public boolean hasChatRoomId() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <code>optional string chatRoomId = 4;</code>
   */
  public java.lang.String getChatRoomId() {
    java.lang.Object ref = chatRoomId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        chatRoomId_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string chatRoomId = 4;</code>
   */
  public com.google.protobuf.ByteString
      getChatRoomIdBytes() {
    java.lang.Object ref = chatRoomId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      chatRoomId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // optional string msgPath = 5;
  public static final int MSGPATH_FIELD_NUMBER = 5;
  private java.lang.Object msgPath_;
  /**
   * <code>optional string msgPath = 5;</code>
   */
  public boolean hasMsgPath() {
    return ((bitField0_ & 0x00000010) == 0x00000010);
  }
  /**
   * <code>optional string msgPath = 5;</code>
   */
  public java.lang.String getMsgPath() {
    java.lang.Object ref = msgPath_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        msgPath_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string msgPath = 5;</code>
   */
  public com.google.protobuf.ByteString
      getMsgPathBytes() {
    java.lang.Object ref = msgPath_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      msgPath_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  // repeated int32 channelId = 6;
  public static final int CHANNELID_FIELD_NUMBER = 6;
  private java.util.List<java.lang.Integer> channelId_;
  /**
   * <code>repeated int32 channelId = 6;</code>
   */
  public java.util.List<java.lang.Integer>
      getChannelIdList() {
    return channelId_;
  }
  /**
   * <code>repeated int32 channelId = 6;</code>
   */
  public int getChannelIdCount() {
    return channelId_.size();
  }
  /**
   * <code>repeated int32 channelId = 6;</code>
   */
  public int getChannelId(int index) {
    return channelId_.get(index);
  }

  private void initFields() {
    messageId_ = "";
    message_ = "";
    chatPath_ = "";
    chatRoomId_ = "";
    msgPath_ = "";
    channelId_ = java.util.Collections.emptyList();
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    if (!hasMessageId()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeBytes(1, getMessageIdBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeBytes(2, getMessageBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeBytes(3, getChatPathBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeBytes(4, getChatRoomIdBytes());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      output.writeBytes(5, getMsgPathBytes());
    }
    for (int i = 0; i < channelId_.size(); i++) {
      output.writeInt32(6, channelId_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, getMessageIdBytes());
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, getMessageBytes());
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, getChatPathBytes());
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, getChatRoomIdBytes());
    }
    if (((bitField0_ & 0x00000010) == 0x00000010)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, getMsgPathBytes());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < channelId_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(channelId_.get(i));
      }
      size += dataSize;
      size += 1 * getChannelIdList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  protected java.lang.Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static com.whosbean.newim.entity.ExchangeMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.whosbean.newim.entity.ExchangeMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.whosbean.newim.entity.ExchangeMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.whosbean.newim.entity.ExchangeMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.whosbean.newim.entity.ExchangeMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.whosbean.newim.entity.ExchangeMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static com.whosbean.newim.entity.ExchangeMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static com.whosbean.newim.entity.ExchangeMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static com.whosbean.newim.entity.ExchangeMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static com.whosbean.newim.entity.ExchangeMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(com.whosbean.newim.entity.ExchangeMessage prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code im.ExchangeMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements com.whosbean.newim.entity.ExchangeMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.whosbean.newim.entity.EntitySchema.internal_static_im_ExchangeMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.whosbean.newim.entity.EntitySchema.internal_static_im_ExchangeMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.whosbean.newim.entity.ExchangeMessage.class, com.whosbean.newim.entity.ExchangeMessage.Builder.class);
    }

    // Construct using com.whosbean.newim.entity.ExchangeMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      messageId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      message_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      chatPath_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      chatRoomId_ = "";
      bitField0_ = (bitField0_ & ~0x00000008);
      msgPath_ = "";
      bitField0_ = (bitField0_ & ~0x00000010);
      channelId_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000020);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.whosbean.newim.entity.EntitySchema.internal_static_im_ExchangeMessage_descriptor;
    }

    public com.whosbean.newim.entity.ExchangeMessage getDefaultInstanceForType() {
      return com.whosbean.newim.entity.ExchangeMessage.getDefaultInstance();
    }

    public com.whosbean.newim.entity.ExchangeMessage build() {
      com.whosbean.newim.entity.ExchangeMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.whosbean.newim.entity.ExchangeMessage buildPartial() {
      com.whosbean.newim.entity.ExchangeMessage result = new com.whosbean.newim.entity.ExchangeMessage(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.messageId_ = messageId_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.message_ = message_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.chatPath_ = chatPath_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.chatRoomId_ = chatRoomId_;
      if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
        to_bitField0_ |= 0x00000010;
      }
      result.msgPath_ = msgPath_;
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        channelId_ = java.util.Collections.unmodifiableList(channelId_);
        bitField0_ = (bitField0_ & ~0x00000020);
      }
      result.channelId_ = channelId_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.whosbean.newim.entity.ExchangeMessage) {
        return mergeFrom((com.whosbean.newim.entity.ExchangeMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.whosbean.newim.entity.ExchangeMessage other) {
      if (other == com.whosbean.newim.entity.ExchangeMessage.getDefaultInstance()) return this;
      if (other.hasMessageId()) {
        bitField0_ |= 0x00000001;
        messageId_ = other.messageId_;
        onChanged();
      }
      if (other.hasMessage()) {
        bitField0_ |= 0x00000002;
        message_ = other.message_;
        onChanged();
      }
      if (other.hasChatPath()) {
        bitField0_ |= 0x00000004;
        chatPath_ = other.chatPath_;
        onChanged();
      }
      if (other.hasChatRoomId()) {
        bitField0_ |= 0x00000008;
        chatRoomId_ = other.chatRoomId_;
        onChanged();
      }
      if (other.hasMsgPath()) {
        bitField0_ |= 0x00000010;
        msgPath_ = other.msgPath_;
        onChanged();
      }
      if (!other.channelId_.isEmpty()) {
        if (channelId_.isEmpty()) {
          channelId_ = other.channelId_;
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          ensureChannelIdIsMutable();
          channelId_.addAll(other.channelId_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      if (!hasMessageId()) {
        
        return false;
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.whosbean.newim.entity.ExchangeMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.whosbean.newim.entity.ExchangeMessage) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // required string messageId = 1;
    private java.lang.Object messageId_ = "";
    /**
     * <code>required string messageId = 1;</code>
     */
    public boolean hasMessageId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string messageId = 1;</code>
     */
    public java.lang.String getMessageId() {
      java.lang.Object ref = messageId_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        messageId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string messageId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      java.lang.Object ref = messageId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string messageId = 1;</code>
     */
    public Builder setMessageId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      messageId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string messageId = 1;</code>
     */
    public Builder clearMessageId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      messageId_ = getDefaultInstance().getMessageId();
      onChanged();
      return this;
    }
    /**
     * <code>required string messageId = 1;</code>
     */
    public Builder setMessageIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      messageId_ = value;
      onChanged();
      return this;
    }

    // optional string message = 2;
    private java.lang.Object message_ = "";
    /**
     * <code>optional string message = 2;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string message = 2;</code>
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string message = 2;</code>
     */
    public Builder clearMessage() {
      bitField0_ = (bitField0_ & ~0x00000002);
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>optional string message = 2;</code>
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      message_ = value;
      onChanged();
      return this;
    }

    // optional string chatPath = 3;
    private java.lang.Object chatPath_ = "";
    /**
     * <code>optional string chatPath = 3;</code>
     */
    public boolean hasChatPath() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string chatPath = 3;</code>
     */
    public java.lang.String getChatPath() {
      java.lang.Object ref = chatPath_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        chatPath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string chatPath = 3;</code>
     */
    public com.google.protobuf.ByteString
        getChatPathBytes() {
      java.lang.Object ref = chatPath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chatPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string chatPath = 3;</code>
     */
    public Builder setChatPath(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      chatPath_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string chatPath = 3;</code>
     */
    public Builder clearChatPath() {
      bitField0_ = (bitField0_ & ~0x00000004);
      chatPath_ = getDefaultInstance().getChatPath();
      onChanged();
      return this;
    }
    /**
     * <code>optional string chatPath = 3;</code>
     */
    public Builder setChatPathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      chatPath_ = value;
      onChanged();
      return this;
    }

    // optional string chatRoomId = 4;
    private java.lang.Object chatRoomId_ = "";
    /**
     * <code>optional string chatRoomId = 4;</code>
     */
    public boolean hasChatRoomId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string chatRoomId = 4;</code>
     */
    public java.lang.String getChatRoomId() {
      java.lang.Object ref = chatRoomId_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        chatRoomId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string chatRoomId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getChatRoomIdBytes() {
      java.lang.Object ref = chatRoomId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chatRoomId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string chatRoomId = 4;</code>
     */
    public Builder setChatRoomId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      chatRoomId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string chatRoomId = 4;</code>
     */
    public Builder clearChatRoomId() {
      bitField0_ = (bitField0_ & ~0x00000008);
      chatRoomId_ = getDefaultInstance().getChatRoomId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string chatRoomId = 4;</code>
     */
    public Builder setChatRoomIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      chatRoomId_ = value;
      onChanged();
      return this;
    }

    // optional string msgPath = 5;
    private java.lang.Object msgPath_ = "";
    /**
     * <code>optional string msgPath = 5;</code>
     */
    public boolean hasMsgPath() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string msgPath = 5;</code>
     */
    public java.lang.String getMsgPath() {
      java.lang.Object ref = msgPath_;
      if (!(ref instanceof java.lang.String)) {
        java.lang.String s = ((com.google.protobuf.ByteString) ref)
            .toStringUtf8();
        msgPath_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string msgPath = 5;</code>
     */
    public com.google.protobuf.ByteString
        getMsgPathBytes() {
      java.lang.Object ref = msgPath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string msgPath = 5;</code>
     */
    public Builder setMsgPath(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      msgPath_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string msgPath = 5;</code>
     */
    public Builder clearMsgPath() {
      bitField0_ = (bitField0_ & ~0x00000010);
      msgPath_ = getDefaultInstance().getMsgPath();
      onChanged();
      return this;
    }
    /**
     * <code>optional string msgPath = 5;</code>
     */
    public Builder setMsgPathBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      msgPath_ = value;
      onChanged();
      return this;
    }

    // repeated int32 channelId = 6;
    private java.util.List<java.lang.Integer> channelId_ = java.util.Collections.emptyList();
    private void ensureChannelIdIsMutable() {
      if (!((bitField0_ & 0x00000020) == 0x00000020)) {
        channelId_ = new java.util.ArrayList<java.lang.Integer>(channelId_);
        bitField0_ |= 0x00000020;
       }
    }
    /**
     * <code>repeated int32 channelId = 6;</code>
     */
    public java.util.List<java.lang.Integer>
        getChannelIdList() {
      return java.util.Collections.unmodifiableList(channelId_);
    }
    /**
     * <code>repeated int32 channelId = 6;</code>
     */
    public int getChannelIdCount() {
      return channelId_.size();
    }
    /**
     * <code>repeated int32 channelId = 6;</code>
     */
    public int getChannelId(int index) {
      return channelId_.get(index);
    }
    /**
     * <code>repeated int32 channelId = 6;</code>
     */
    public Builder setChannelId(
        int index, int value) {
      ensureChannelIdIsMutable();
      channelId_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 channelId = 6;</code>
     */
    public Builder addChannelId(int value) {
      ensureChannelIdIsMutable();
      channelId_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 channelId = 6;</code>
     */
    public Builder addAllChannelId(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureChannelIdIsMutable();
      super.addAll(values, channelId_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 channelId = 6;</code>
     */
    public Builder clearChannelId() {
      channelId_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:im.ExchangeMessage)
  }

  static {
    defaultInstance = new ExchangeMessage(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:im.ExchangeMessage)
}

