// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entity_schema.proto

package com.whosbean.newim.entity;

public interface ChatStatusOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required string sender = 1;
  /**
   * <code>required string sender = 1;</code>
   */
  boolean hasSender();
  /**
   * <code>required string sender = 1;</code>
   */
  java.lang.String getSender();
  /**
   * <code>required string sender = 1;</code>
   */
  com.google.protobuf.ByteString
      getSenderBytes();

  // required int32 syncMark = 2;
  /**
   * <code>required int32 syncMark = 2;</code>
   */
  boolean hasSyncMark();
  /**
   * <code>required int32 syncMark = 2;</code>
   */
  int getSyncMark();
}
