// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entity_schema.proto

package com.whosbean.newim.entity;

public interface ChatMessageOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // required string boxid = 1;
  /**
   * <code>required string boxid = 1;</code>
   */
  boolean hasBoxid();
  /**
   * <code>required string boxid = 1;</code>
   */
  java.lang.String getBoxid();
  /**
   * <code>required string boxid = 1;</code>
   */
  com.google.protobuf.ByteString
      getBoxidBytes();

  // required int32 group = 2 [default = 0];
  /**
   * <code>required int32 group = 2 [default = 0];</code>
   */
  boolean hasGroup();
  /**
   * <code>required int32 group = 2 [default = 0];</code>
   */
  int getGroup();

  // optional string uuid = 3;
  /**
   * <code>optional string uuid = 3;</code>
   */
  boolean hasUuid();
  /**
   * <code>optional string uuid = 3;</code>
   */
  java.lang.String getUuid();
  /**
   * <code>optional string uuid = 3;</code>
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  // optional string sender = 4;
  /**
   * <code>optional string sender = 4;</code>
   */
  boolean hasSender();
  /**
   * <code>optional string sender = 4;</code>
   */
  java.lang.String getSender();
  /**
   * <code>optional string sender = 4;</code>
   */
  com.google.protobuf.ByteString
      getSenderBytes();

  // optional string receiver = 5;
  /**
   * <code>optional string receiver = 5;</code>
   */
  boolean hasReceiver();
  /**
   * <code>optional string receiver = 5;</code>
   */
  java.lang.String getReceiver();
  /**
   * <code>optional string receiver = 5;</code>
   */
  com.google.protobuf.ByteString
      getReceiverBytes();

  // optional string body = 6;
  /**
   * <code>optional string body = 6;</code>
   */
  boolean hasBody();
  /**
   * <code>optional string body = 6;</code>
   */
  java.lang.String getBody();
  /**
   * <code>optional string body = 6;</code>
   */
  com.google.protobuf.ByteString
      getBodyBytes();

  // required .im.ChatMessage.MessageType mtype = 7 [default = SYNC];
  /**
   * <code>required .im.ChatMessage.MessageType mtype = 7 [default = SYNC];</code>
   */
  boolean hasMtype();
  /**
   * <code>required .im.ChatMessage.MessageType mtype = 7 [default = SYNC];</code>
   */
  com.whosbean.newim.entity.ChatMessage.MessageType getMtype();

  // required .im.ChatMessage.ChatOp op = 8 [default = ACK];
  /**
   * <code>required .im.ChatMessage.ChatOp op = 8 [default = ACK];</code>
   */
  boolean hasOp();
  /**
   * <code>required .im.ChatMessage.ChatOp op = 8 [default = ACK];</code>
   */
  com.whosbean.newim.entity.ChatMessage.ChatOp getOp();
}
